http:
  routers:
    arcane:
      rule: "Host(`arcane.mi-dominio.es`)"
      service: arcane
      entryPoints:
        - websecure
      middlewares:
        - secure-headers

  services:
    arcane:
      loadBalancer:
        servers:
          - url: "http://localhost:3552"
