services:
  socket-proxy:
    image: tecnativa/docker-socket-proxy:latest
    container_name: socket-proxy
    environment:
      - DISABLE_IPV6=1
      - EVENTS=1
      - PING=1
      - VERSION=1
      # Security critical
      - AUTH=0
      - SECRETS=0
      - POST=1
      # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=1
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=0
      - PLUGINS=0
      - SERVICES=0
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=0
      - VOLUMES=1
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - socket-proxy
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true

  arcane-agent:
    image: ghcr.io/getarcaneapp/arcane-headless:latest
    container_name: arcane-agent
    ports:
      - "3553:3553"
    environment:
      TZ: ${TZ}
      PUID: ${PUID}
      PGID: ${PGID}
      AGENT_MODE: true
      AGENT_TOKEN: ${AGENT_TOKEN}
      MANAGER_API_URL: "http://${ARCANE_MAIN_IP}:${ARCANE_MAIN_PORT}"
      ANALYTICS_DISABLED: "true"
      DOCKER_HOST: tcp://socket-proxy:2375
    volumes:
      - ${DOCKER_BASE}/arcane-agent:/app/data
    cgroup: host
    restart: unless-stopped
    networks:
      - socket-proxy
    depends_on:
      - socket-proxy

networks:
  socket-proxy:
    external: true
    name: socket-proxy